package com.hendall.surveyrest.entities;
// Generated Jan 25, 2016 4:41:12 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AnswersId generated by hbm2java
 */
@Embeddable
public class AnswersId implements java.io.Serializable {

	private int userSurverAccessAnswersKey;
	private int htmlControlId;

	public AnswersId() {
	}

	public AnswersId(int userSurverAccessAnswersKey, int htmlControlId) {
		this.userSurverAccessAnswersKey = userSurverAccessAnswersKey;
		this.htmlControlId = htmlControlId;
	}

	@Column(name = "User_Surver_Access_Answers_Key", nullable = false)
	public int getUserSurverAccessAnswersKey() {
		return this.userSurverAccessAnswersKey;
	}

	public void setUserSurverAccessAnswersKey(int userSurverAccessAnswersKey) {
		this.userSurverAccessAnswersKey = userSurverAccessAnswersKey;
	}

	@Column(name = "Html_Control_Id", nullable = false)
	public int getHtmlControlId() {
		return this.htmlControlId;
	}

	public void setHtmlControlId(int htmlControlId) {
		this.htmlControlId = htmlControlId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnswersId))
			return false;
		AnswersId castOther = (AnswersId) other;

		return (this.getUserSurverAccessAnswersKey() == castOther.getUserSurverAccessAnswersKey())
				&& (this.getHtmlControlId() == castOther.getHtmlControlId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserSurverAccessAnswersKey();
		result = 37 * result + this.getHtmlControlId();
		return result;
	}

}
