package com.hendall.surveyrest.entities;
// Generated Feb 11, 2016 11:15:33 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StatesLu generated by hbm2java
 */
@Entity
@Table(name = "states_lu", catalog = "survey")
public class StatesLu extends BaseEntity  implements java.io.Serializable {

	private String stateCode;
	private String stateName;
	
	private Set<ProvidersLu> providersLus = new HashSet<ProvidersLu>(0);

	public StatesLu() {
	}

	public StatesLu(String stateCode, String stateName) {
		this.stateCode = stateCode;
		this.stateName = stateName;
		
	}

	public StatesLu(String stateCode, String stateName, Date createDate,
			Integer modifyUser, Set<ProvidersLu> providersLus) {
		this.stateCode = stateCode;
		this.stateName = stateName;
		this.providersLus = providersLus;
	}

	@Id

	@Column(name = "State_Code", unique = true, nullable = false, length = 2)
	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	@Column(name = "State_Name", nullable = false, length = 45)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statesLu")
	public Set<ProvidersLu> getProvidersLus() {
		return this.providersLus;
	}

	public void setProvidersLus(Set<ProvidersLu> providersLus) {
		this.providersLus = providersLus;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((stateCode == null) ? 0 : stateCode.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		StatesLu other = (StatesLu) obj;
		if (stateCode == null) {
			if (other.stateCode != null)
				return false;
		} else if (!stateCode.equals(other.stateCode))
			return false;
		return true;
	}
	
	

}
