package com.hendall.surveyrest.entities;
// Generated Jan 25, 2016 2:51:30 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SurveyTypeLu generated by hbm2java
 */
@Entity
@Table(name = "survey_type_lu")
public class SurveyTypeLu extends BaseEntity implements java.io.Serializable {

	private Integer surveyTypeKey;
	private String surveyNum;
	private String surveyName;
	private long surverVersion;

	private Set<Survey> surveys = new HashSet<Survey>(0);

	public SurveyTypeLu() {
	}

	public SurveyTypeLu(String surveyNum, String surveyName, long surverVersion, Date createDate, int createUser) {
		this.surveyNum = surveyNum;
		this.surveyName = surveyName;
		this.surverVersion = surverVersion;

	}

	public SurveyTypeLu(String surveyNum, String surveyName, long surverVersion, Date createDate, int createUser,
			Date modifyDate, Integer modifyUser, Set<Survey> surveys) {
		this.surveyNum = surveyNum;
		this.surveyName = surveyName;
		this.surverVersion = surverVersion;

		this.surveys = surveys;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Survey_Type_Key", unique = true, nullable = false)
	public Integer getSurveyTypeKey() {
		return this.surveyTypeKey;
	}

	public void setSurveyTypeKey(Integer surveyTypeKey) {
		this.surveyTypeKey = surveyTypeKey;
	}

	@Column(name = "Survey_Num", nullable = false, length = 45)
	public String getSurveyNum() {
		return this.surveyNum;
	}

	public void setSurveyNum(String surveyNum) {
		this.surveyNum = surveyNum;
	}

	@Column(name = "Survey_Name", nullable = false, length = 500)
	public String getSurveyName() {
		return this.surveyName;
	}

	public void setSurveyName(String surveyName) {
		this.surveyName = surveyName;
	}

	@Column(name = "Surver_Version", nullable = false, precision = 10, scale = 0)
	public long getSurverVersion() {
		return this.surverVersion;
	}

	public void setSurverVersion(long surverVersion) {
		this.surverVersion = surverVersion;
	}

	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "surveyTypeLu")
	public Set<Survey> getSurveys() {
		return this.surveys;
	}

	public void setSurveys(Set<Survey> surveys) {
		this.surveys = surveys;
	}

}
