package com.hendall.surveyrest.entities;
// Generated Jan 25, 2016 2:51:30 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", uniqueConstraints = { @UniqueConstraint(columnNames = "email"),
		@UniqueConstraint(columnNames = "UserId") })
public class Users implements java.io.Serializable {

	private Integer userKey;
	private String userId;
	private String password;
	private String firstName;
	private String lastName;
	private String email;
	private int role;
	private String state;
	private Set<Survey> surveys = new HashSet<Survey>(0);
	private Set<UserSurveyAccess> userSurveyAccesses = new HashSet<UserSurveyAccess>(0);

	public Users() {
	}

	public Users(String userId, String password, String firstName, String lastName, String email, int role) {
		this.userId = userId;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.role = role;
	}

	public Users(String userId, String password, String firstName, String lastName, String email, int role,
			Set<Survey> surveys, Set<UserSurveyAccess> userSurveyAccesses) {
		this.userId = userId;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.role = role;
		this.surveys = surveys;
		this.userSurveyAccesses = userSurveyAccesses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "User_Key", unique = true, nullable = false)
	public Integer getUserKey() {
		return this.userKey;
	}

	public void setUserKey(Integer userKey) {
		this.userKey = userKey;
	}

	@Column(name = "UserId", unique = true, nullable = false, length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "Password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "First_Name", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "Last_Name", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", unique = true, nullable = false, length = 150)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	@Column(name = "state", unique = true, nullable = false, length = 3)
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "role", nullable = false)
	public int getRole() {
		return this.role;
	}

	public void setRole(int role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Survey> getSurveys() {
		return this.surveys;
	}

	public void setSurveys(Set<Survey> surveys) {
		this.surveys = surveys;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserSurveyAccess> getUserSurveyAccesses() {
		return this.userSurveyAccesses;
	}

	public void setUserSurveyAccesses(Set<UserSurveyAccess> userSurveyAccesses) {
		this.userSurveyAccesses = userSurveyAccesses;
	}

}
