package com.hendall.survey.services.entities;
// Generated Jan 25, 2016 4:41:12 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Answers generated by hbm2java
 */
@Entity
@Table(name = "answers")
public class Answers extends BaseEntity implements java.io.Serializable {

	private AnswersId id;
	private UserSurveyAccess userSurveyAccess;
	private String answer;



	public Answers() {
	}

	public Answers(AnswersId id, UserSurveyAccess userSurveyAccess, String answer, Date createDate, int createUser) {
		this.id = id;
		this.userSurveyAccess = userSurveyAccess;
		this.answer = answer;
		
	}

	public Answers(AnswersId id, UserSurveyAccess userSurveyAccess, String answer, Date createDate, int createUser,
			Date modifyDate, Integer modifyUser) {
		this.id = id;
		this.userSurveyAccess = userSurveyAccess;
		this.answer = answer;
		
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userSurverAccessAnswersKey", column = @Column(name = "User_Surver_Access_Answers_Key", nullable = false) ),
			@AttributeOverride(name = "htmlControlId", column = @Column(name = "Html_Control_Id", nullable = false) ) })
	public AnswersId getId() {
		return this.id;
	}

	public void setId(AnswersId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_Surver_Access_Answers_Key", nullable = false, insertable = false, updatable = false)
	public UserSurveyAccess getUserSurveyAccess() {
		return this.userSurveyAccess;
	}

	public void setUserSurveyAccess(UserSurveyAccess userSurveyAccess) {
		this.userSurveyAccess = userSurveyAccess;
	}

	@Column(name = "Answer",  length = 65535)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	

	
}
