package com.hendall.survey.services.entities;
// Generated Feb 11, 2016 11:15:33 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProvidersLu generated by hbm2java
 */
@Entity
@Table(name = "providers_lu", catalog = "survey")
public class ProvidersLu implements java.io.Serializable {

	private Integer providerKey;
	private StatesLu statesLu;
	private String region;
	private String ccn;
	private String prvdrIntrnlNum;
	private String facIntrnlId;
	private String facilityName;
	private String typeOfOwnership;
	private String streetAddress;
	private String city;
	private String zipCode;
	private String county;
	private String phoneNumber;
	private String stateRegion;
	private String certifiedBeds;
	private String providerType;
	private String providerSubtype;
	private String deemedStatus;
	private String deemingAgency;

	public ProvidersLu() {
	}

	public ProvidersLu(StatesLu statesLu, String region, String ccn, String prvdrIntrnlNum, String facIntrnlId,
			String facilityName, String typeOfOwnership, String streetAddress, String city, String zipCode,
			String county, String phoneNumber, String stateRegion, String certifiedBeds, String providerType,
			String providerSubtype, String deemedStatus, String deemingAgency) {
		this.statesLu = statesLu;
		this.region = region;
		this.ccn = ccn;
		this.prvdrIntrnlNum = prvdrIntrnlNum;
		this.facIntrnlId = facIntrnlId;
		this.facilityName = facilityName;
		this.typeOfOwnership = typeOfOwnership;
		this.streetAddress = streetAddress;
		this.city = city;
		this.zipCode = zipCode;
		this.county = county;
		this.phoneNumber = phoneNumber;
		this.stateRegion = stateRegion;
		this.certifiedBeds = certifiedBeds;
		this.providerType = providerType;
		this.providerSubtype = providerSubtype;
		this.deemedStatus = deemedStatus;
		this.deemingAgency = deemingAgency;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Provider_Key", unique = true, nullable = false)
	public Integer getProviderKey() {
		return this.providerKey;
	}

	public void setProviderKey(Integer providerKey) {
		this.providerKey = providerKey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "State")
	public StatesLu getStatesLu() {
		return this.statesLu;
	}

	public void setStatesLu(StatesLu statesLu) {
		this.statesLu = statesLu;
	}

	@Column(name = "Region")
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "CCN")
	public String getCcn() {
		return this.ccn;
	}

	public void setCcn(String ccn) {
		this.ccn = ccn;
	}

	@Column(name = "PRVDR_INTRNL_NUM")
	public String getPrvdrIntrnlNum() {
		return this.prvdrIntrnlNum;
	}

	public void setPrvdrIntrnlNum(String prvdrIntrnlNum) {
		this.prvdrIntrnlNum = prvdrIntrnlNum;
	}

	@Column(name = "FAC_INTRNL_ID")
	public String getFacIntrnlId() {
		return this.facIntrnlId;
	}

	public void setFacIntrnlId(String facIntrnlId) {
		this.facIntrnlId = facIntrnlId;
	}

	@Column(name = "Facility_Name")
	public String getFacilityName() {
		return this.facilityName;
	}

	public void setFacilityName(String facilityName) {
		this.facilityName = facilityName;
	}

	@Column(name = "Type_of_Ownership")
	public String getTypeOfOwnership() {
		return this.typeOfOwnership;
	}

	public void setTypeOfOwnership(String typeOfOwnership) {
		this.typeOfOwnership = typeOfOwnership;
	}

	@Column(name = "Street_Address")
	public String getStreetAddress() {
		return this.streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	@Column(name = "City")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "Zip_Code")
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "County")
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "Phone_Number")
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "State_Region")
	public String getStateRegion() {
		return this.stateRegion;
	}

	public void setStateRegion(String stateRegion) {
		this.stateRegion = stateRegion;
	}

	@Column(name = "Certified_Beds")
	public String getCertifiedBeds() {
		return this.certifiedBeds;
	}

	public void setCertifiedBeds(String certifiedBeds) {
		this.certifiedBeds = certifiedBeds;
	}

	@Column(name = "Provider_Type")
	public String getProviderType() {
		return this.providerType;
	}

	public void setProviderType(String providerType) {
		this.providerType = providerType;
	}

	@Column(name = "Provider_Subtype")
	public String getProviderSubtype() {
		return this.providerSubtype;
	}

	public void setProviderSubtype(String providerSubtype) {
		this.providerSubtype = providerSubtype;
	}

	@Column(name = "Deemed_Status")
	public String getDeemedStatus() {
		return this.deemedStatus;
	}

	public void setDeemedStatus(String deemedStatus) {
		this.deemedStatus = deemedStatus;
	}

	@Column(name = "Deeming_Agency")
	public String getDeemingAgency() {
		return this.deemingAgency;
	}

	public void setDeemingAgency(String deemingAgency) {
		this.deemingAgency = deemingAgency;
	}

}
