package com.hendall.survey.services.entities;
// Generated Jan 25, 2016 4:41:12 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserSurveyAccess generated by hbm2java
 */
@Entity
@Table(name = "user_survey_access")
public class UserSurveyAccess extends BaseEntity implements java.io.Serializable {

	private Integer userSurveyKey;
	private Survey survey;
	private Users users;
	private String status;
	private Set<Answers> answerses = new HashSet<Answers>(0);

	public UserSurveyAccess() {
	}

	public UserSurveyAccess(Survey survey, Users users) {
		this.survey = survey;
		this.users = users;
	}

	public UserSurveyAccess(Survey survey, Users users, String status, Date createDate, Integer createUser,
			Date modifyDate, Integer modifyUser, Set<Answers> answerses) {
		this.survey = survey;
		this.users = users;
		this.status = status;
		this.answerses = answerses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "User_Survey_Key", unique = true, nullable = false)
	public Integer getUserSurveyKey() {
		return this.userSurveyKey;
	}

	public void setUserSurveyKey(Integer userSurveyKey) {
		this.userSurveyKey = userSurveyKey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Survey_key", nullable = false)
	public Survey getSurvey() {
		return this.survey;
	}

	public void setSurvey(Survey survey) {
		this.survey = survey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_Key", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "Status", length = 100)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userSurveyAccess")
	public Set<Answers> getAnswerses() {
		return this.answerses;
	}

	public void setAnswerses(Set<Answers> answerses) {
		this.answerses = answerses;
	}

}
